IMAGE_NAME = "bento/debian-13"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end

    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
        debian.vm.network "forwarded_port", guest: 22, host: 2205, host_ip: "127.0.0.1"
	debian.vm.network "forwarded_port", guest: 80, host: 8805, host_ip: "127.0.0.1"
	config.vm.network "private_network", ip: "192.168.1.5", virtualbox__intnet: "intnet"
        debian.vm.hostname = "zbx01"
    end

    config.vm.provision "file", source: "id_ed25519.pub", destination: "~/.ssh/me.pub"
    config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys

    SHELL

    # Načtení a provedení scriptu install-zabbix-agent2.sh
    config.vm.provision "shell", path: "install-zabbix-agent2.sh"

    # Načtení a provedení scriptu configure-zabbix-agent2.sh
    config.vm.provision "shell", path: "configure-zabbix-agent2.sh"


end
